### ISSUE TITLE
抽選画面の作成

### ISSUE THREAD

**Issue by keiya01** [keiya01/otoshidama-m-front#10]
# Color Code

```
main: #E6BF43
active: rgba(230, 191, 67, 0.6)
twitter: #1DA1F2
```

# TODO

- [ ] Title Component
- [ ] Twitter Auth Component
- [ ] 抽選画面 Page Component
- [ ] 認証リクエスト
  - [ ] Loading Component
  - [ ] Error Component

他に必要な機能があれば教えてください！

**Comment by champon1020** [comment]
とりあえずそんな感じで大丈夫だと思います！
何か思いついたらコメントします！
