### ISSUE TITLE
当選画面の作成

### ISSUE THREAD

**Issue by champon1020** [keiya01/otoshidama-m-front#11]
## TODO

- [ ] 当選画面 Component
- [ ] 別企画のお知らせみたいな？

**Comment by keiya01** [comment]
着手しちゃいます！

**Comment by champon1020** [comment]
お願いします！

あと，gitに関してですが，```issue```とかの```assignee```は担当する人を表すので，担当する人をチェック入れてもらえれば大丈夫です！
https://help.github.com/ja/github/managing-your-work-on-github/filtering-issues-and-pull-requests-by-assignees

**Comment by keiya01** [comment]
なるほど！わかりました！
