### ISSUE TITLE
設定画面の作成

### ISSUE THREAD

**Issue by champon1020** [keiya01/otoshidama-m-front#12]
## TODO

- [x] 抽選状況（人数のみをグラフで？）
- [x] Tweet URL 紐付け

**Comment by keiya01** [comment]
リツイート数といいね数ものせますか？

**Comment by champon1020** [comment]
いいですね！そうしましょう！

**Comment by champon1020** [comment]
chartjsとlodash使ってもいいですか？？

**Comment by champon1020** [comment]
chartjsはグラフ書くようで，lodashは，グラフの設定書くのに結構便利なので...

**Comment by keiya01** [comment]
lodashの機能ってなに使いますか？？
自前で書くの大変そうですかね、、

**Comment by champon1020** [comment]
loadash.mergeを使おうかと思ってます！
自前でも特に大変ではないので，他のものに依存しそうであれば使わなくても問題ないです！

lodash無し
```
defaults.global.animation = false;
defaults.global.line.borderColor: '#F85F73'
```

lodash有り
```
lodash.merge(defaults, {
  global: {
    animation: false,
    line: {
      borderColor: '#F85F73',
     },
  },
});
```

**Comment by champon1020** [comment]
まあこれくらいの機能なら自前で関数作っちゃっても問題なさそうです！

**Comment by keiya01** [comment]
一つの関数だけであればloadash入れるのは重いかなと思ったので、自前で実装できそうならして欲しいです！

**Comment by champon1020** [comment]
わかりました！

**Comment by champon1020** [comment]
質問なのですが，ファボ数とかリツイート数の取得はredux経由で受け取りますか？
それとも直接api叩いて...って感じですか？

**Comment by keiya01** [comment]
ファボ数とかリツイート数って他のコンポーネントで使う可能性ありますかね、、
なければ使用するコンポーネントのみで呼び出すようにした方がわかりやすいのかなと思いました！

**Comment by champon1020** [comment]
わかりました！
他で使うってなっても直接叩いたほうが楽そうですしね！
ありがとうございます！

**Comment by champon1020** [comment]
紐付けやりまーす
