### ISSUE TITLE
セットアップ TODO

### ISSUE THREAD

**Issue by keiya01** [keiya01/otoshidama-m-front#3]
分かりやすいようにissueでTODOを管理します。作業を開始するときはコメントで報告して作業を始めてください！
足りない部分があれば教えていただければ助かります。
よろしくおねがいします！

- [x] linter セットアップ
- [x] docz セットアップ
- [x] react-router セットアップ
- [x] redux セットアップ

**Comment by keiya01** [comment]
docz作業中です！

**Comment by champon1020** [comment]
かしこまりました！
reduxやります！
